from backend.models.camera import Camera
from backend.models.entity import Entity
from backend.models.vehicle import Vehicle
from backend.models.detection import Detection
from backend.models.event import Event
from backend.models.alert import Alert
from backend.models.zone import Zone
from backend.models.watchlist import Watchlist
from backend.models.cross_camera import CrossCameraTrack
from backend.models.association import PersonVehicleAssociation